# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.tmux.conf

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable mouse control
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# true color support (needed for nvim)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# reduce escape time (important for nvim)
set -sg escape-time 0

# extended keys
set -s extended-keys always
set -s extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'

# increase scrollback
set -g history-limit 50000

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# catppuccin
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_text ' #W'
set -g @catppuccin_window_current_text ' #W'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# statusbar
set -g status-position bottom
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
